@startuml Observer
Interface Subject {
  {method} void registerObserver(Observer o)
  {method} void removeObserver(Observer o)
  {method} void notifyObservers()
}

Class WeatherData implements Subject {
  {field} -ArrayList<Observer> observers;
  {field} -float temperature;
  {field} -float humidity;
  {field} -float pressure;

  {method} +void registerObserver(Observer o) {...}
  {method} +void removeObserver(Observer o) {...}
  {method} ~void notifyObservers() {//foreach observer invoke update()}

  {method} +float getTemperature() {...}
  {method} +float getHumidity() {...}
  {method} +float getPressure() {...}
  {method} +void setMeasurements(float t, float h, float p) {...measurementsChanged()}
  {method} -void measurementsChanged() {notifyObservers()}
}


Interface Observer {
  {method} void update(float t, float h, float p)
}

Subject ..> Observer
WeatherData o-> Observer
Observer <|.. CurrentWeatherDisplay
Observer <|.. ForecastDisplay


Class CurrentWeatherDisplay {
  {method} +void update(float t, float h, float p) {...}
  {method} +void display() {...}
}

Class ForecastDisplay {
  {method} +void update(float t, float h, float p) {...}
  {method} +void display() {...}
}


@enduml