@startuml Strategy

skinparam rectangle {
  roundCorner 25
}

rectangle "Client" {
  abstract class Character {
    {field} ~WeaponBehavior weapon
    {field} ~ArmorBehavior armor
    {method} Character(WeaponBehavior w, ArmorBehavior a);
    {method} +void fight();
    {method} +void defend();
    {method} +void setWeaponBehavior(WeaponBehavior w);
    {method} +void setArmorBehavior(ArmorBehavior a);
  }

  class Knight extends Character

  class Wizard extends Character
}

together {
  rectangle "Encapsulated Weapon Behavior" {
    interface WeaponBehavior {
      {method} useWeapon()
    }

    class SwordBehavior implements WeaponBehavior {
      {method} +void useWeapon();
    }

    class MagicBehavior implements WeaponBehavior {
      {method} +void useWeapon();
    }
  }

  rectangle "Encapsulated Armor Behavior" {
    interface ArmorBehavior {
      {method} useArmor()
    }

    class LightArmorBehavior implements ArmorBehavior {
      {method} +void useArmor();
    }

    class HeavyArmorBehavior implements ArmorBehavior {
      {method} +void useArmor();
    }
  }
}


Character --> WeaponBehavior
Character --> ArmorBehavior

Character -[hidden]> WeaponBehavior
WeaponBehavior -[hidden]--> "Encapsulated Armor Behavior"
@enduml